/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimeRouteImport } from './routes/_authenticated/time'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedNotesNoteIdRouteImport } from './routes/_authenticated/notes.$noteId'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'
import { Route as ApiPublicHooksSyncGoogleCalendarRouteImport } from './routes/api/public/hooks/sync-google-calendar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimeRoute = AuthenticatedTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesNoteIdRoute =
  AuthenticatedNotesNoteIdRouteImport.update({
    id: '/$noteId',
    path: '/$noteId',
    getParentRoute: () => AuthenticatedNotesRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)
const ApiPublicHooksSyncGoogleCalendarRoute =
  ApiPublicHooksSyncGoogleCalendarRouteImport.update({
    id: '/api/public/hooks/sync-google-calendar',
    path: '/api/public/hooks/sync-google-calendar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notes': typeof AuthenticatedNotesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/time': typeof AuthenticatedTimeRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/api/public/hooks/sync-google-calendar': typeof ApiPublicHooksSyncGoogleCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notes': typeof AuthenticatedNotesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/time': typeof AuthenticatedTimeRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/api/public/hooks/sync-google-calendar': typeof ApiPublicHooksSyncGoogleCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/time': typeof AuthenticatedTimeRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/api/public/hooks/sync-google-calendar': typeof ApiPublicHooksSyncGoogleCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/courses'
    | '/dashboard'
    | '/notes'
    | '/settings'
    | '/stats'
    | '/tasks'
    | '/time'
    | '/courses/$courseId'
    | '/notes/$noteId'
    | '/api/public/hooks/sync-google-calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/courses'
    | '/dashboard'
    | '/notes'
    | '/settings'
    | '/stats'
    | '/tasks'
    | '/time'
    | '/courses/$courseId'
    | '/notes/$noteId'
    | '/api/public/hooks/sync-google-calendar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/notes'
    | '/_authenticated/settings'
    | '/_authenticated/stats'
    | '/_authenticated/tasks'
    | '/_authenticated/time'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/notes/$noteId'
    | '/api/public/hooks/sync-google-calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSyncGoogleCalendarRoute: typeof ApiPublicHooksSyncGoogleCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/time': {
      id: '/_authenticated/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthenticatedTimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/$noteId': {
      id: '/_authenticated/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedNotesRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/api/public/hooks/sync-google-calendar': {
      id: '/api/public/hooks/sync-google-calendar'
      path: '/api/public/hooks/sync-google-calendar'
      fullPath: '/api/public/hooks/sync-google-calendar'
      preLoaderRoute: typeof ApiPublicHooksSyncGoogleCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedNotesRouteChildren {
  AuthenticatedNotesNoteIdRoute: typeof AuthenticatedNotesNoteIdRoute
}

const AuthenticatedNotesRouteChildren: AuthenticatedNotesRouteChildren = {
  AuthenticatedNotesNoteIdRoute: AuthenticatedNotesNoteIdRoute,
}

const AuthenticatedNotesRouteWithChildren =
  AuthenticatedNotesRoute._addFileChildren(AuthenticatedNotesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTimeRoute: typeof AuthenticatedTimeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTimeRoute: AuthenticatedTimeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSyncGoogleCalendarRoute: ApiPublicHooksSyncGoogleCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
